branches:
  only:
    - master
    - develop
    - /^issue.*$/

notifications:
  slack:
    secure: "a8YICVgxrxDWGRytxE1btfADbQEsSlIoxigk8bwuK0RWfuRQVlWkfB1eRpAmSVbyxeMbVH4D5rY7b7R4mH6erfCB1wEsh5nMrataBzPa5AR3zaqu6cYYUOpZJQfMjGCUBtH0xqcC4YWGmqdxSfpNGV+xyTG9WKTuOirz0elZT9NqlgmXrGjn+BamiuTC8I0KYb3Pmv/WWP012rKzJUb+D0I4OLE0iQgGC5gVfB9RxtB+2ZuhtLcSdDpI9ugkRTNV/q6bfZ+iZLZY5vLh9DtJiOT7I9j3KkrrD3+kJs9z8AsIHUyIEsgwsD6ZkMboEpPPnrXXMsENaj7f+IxugqURslgANqnPgl1cR8YHA865pMY1PUD9oWk5yPtQZ3CLrp4Tr/DNF3NI58QWwQxnGkRQERMxPiECxU6if5PQmX/utgmd36TGZPGb1iLYo3RAIok6EyhYsz8OdYSkbNMvMWcnpw17Zbi84izNJ9KslK7uwheTZ0cPwKeKFm9Tj801CM+9Qa22JxSjdSx45NIrcpdiAihb/cpmiPSsLyDqSyLl6Z8ABFELl70EJTJQ1+V1u9AsY0cMcvM3xe9Ra1oR1ydydzyjnQpxTowcCcKoyiDSukRuRwpQYq8galvLKdvhQmZkpWA/klUFT4X24AVFCtYpFCzVdHUmA7qHOAK2ezWT+OA="
    
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.1-DEVELOPMENT-SNAPSHOT-2018-02-26-a
    - os: osx
      osx_image: xcode8.3
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3
    - os: osx
      osx_image: xcode9.3beta
      sudo: required
      env: SWIFT_SNAPSHOT=4.1-DEVELOPMENT-SNAPSHOT-2018-02-26-a

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
